create table player (
	player_key text primary key,
	constraint valid_player_key check (player_key like ('oe:player:%'))
);

create table player_alias (
	id serial primary key,
	alias text not null,
	player_key text references player (player_key)
);

create table team (
	team_key text primary key
	constraint valid_team_key check (team_key like ('oe:team:%'))
);

create table match_stat (
	match_key text primary key,
	league text not null,
	year int not null,
	playoffs bool not null,
	date timestamp not null,
	game int not null,
	patch real not null,
	side text not null
	constraint check_side check (side in ('Blue', 'Red')),
	teamname text not null,
	length int not null,
	result bool not null,
	inhibitors int not null,
	opp_inhibitors int not null,
	gold_spent_percent_difference numeric (3, 10) not null,
	gold_percent_rating numeric (3, 10) not null
);

create table player_stat (
	player_stat_key text primary key,
	match_key text references match_stat(match_key),
	player_key text references player(player_key),
	position text not null
	constraint check_position check (position in ('top', 'jng', 'mid', 'bot', 'sup')),
	length int,
	result bool,
	inhibitors int,
	opp_inhibitors int,
	gold_spent_percent_difference numeric (3, 10),
	gold_percent_rating numeric (3, 10),
	kills int,
	deaths int,
	assists int,
	teamkills int,
	teamdeaths int,
	doublekills int,
	triplekills int,
	quadrakills int,
	pentakills int,
	first_blood int,
	first_blood_kill int,
	first_blood_assist int,
	dmg_to_champs int,
	dmg_per_min numeric(10, 10),
	dmg_share numeric(3, 10),
	dmg_taken_per_min numeric (10, 10),
	dmg_mitigated_per_min numeric (10, 10),
	wards_placed int,
	wards_per_min numeric (3, 10),
	control_wards_bought int,
	vision_score int,
	vision_score_per_min numeric (3, 10),
	total_gold int,
	earned_gold int,
	earned_gold_per_min numeric (10, 10),
	earned_gold_share numeric (3, 10),
	gold_spent int,
	total_cs int,
	cs_per_min numeric (5, 10),
	gold_at_10 int,
	xp_at_10 int,
	cs_at_10 int,
	opp_gold_at_10 int,
	opp_xp_at_10 int,
	opp_cs_at_10 int,
	gold_diff_at_10 int,
	xp_diff_at_10 int,
	cs_diff_at_10 int,
	kills_at_10 int,
	assists_at_10 int,
	deaths_at_10 int,
	opp_kills_at_10 int,
	opp_assists_at_10 int,
	opp_deaths_at_10 int,
	gold_at_15 int,
	xp_at_15 int,
	cs_at_15 int,
	opp_gold_at_15 int,
	opp_xp_at_15 int,
	opp_cs_at_15 int,
	gold_diff_at_15 int,
	xp_diff_at_15 int,
	cs_diff_at_15 int,
	kills_at_15 int,
	assists_at_15 int,
	deaths_at_15 int,
	opp_kills_at_15 int,
	opp_assists_at_15 int,
	opp_deaths_at_15 int,
	gold_at_20 int,
	xp_at_20 int,
	cs_at_20 int,
	opp_gold_at_20 int,
	opp_xp_at_20 int,
	opp_cs_at_20 int,
	gold_diff_at_20 int,
	xp_diff_at_20 int,
	cs_diff_at_20 int,
	kills_at_20 int,
	assists_at_20 int,
	deaths_at_20 int,
	opp_kills_at_20 int,
	opp_assists_at_20 int,
	opp_deaths_at_20 int,
	gold_at_25 int,
	xp_at_25 int,
	cs_at_25 int,
	opp_gold_at_25 int,
	opp_xp_at_25 int,
	opp_cs_at_25 int,
	gold_diff_at_25 int,
	xp_diff_at_25 int,
	cs_diff_at_25 int,
	kills_at_25 int,
	assists_at_25 int,
	deaths_at_25 int,
	opp_kills_at_25 int,
	opp_assists_at_25 int,
	opp_deaths_at_25 int
);